#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="3.1.3/processmaker-3.1.3-community.tar.gz"
URL="http://sourceforge.net/projects/processmaker/files/ProcessMaker/$VERSION"

dl $URL /usr/local/src

