#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.0/2.0.45/processmaker-2.0.45.tar.gz"
URL="http://sourceforge.net/projects/processmaker/files/ProcessMaker/$VERSION"

dl $URL /usr/local/src

