#!/bin/sh -ex

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/processmaker

# unpack and set required permissions
tar -zxf $SRC/processmaker-*.tar.gz -C $(dirname $WEBROOT)
rm $SRC/processmaker-*.tar.gz
chown -R www-data:www-data $WEBROOT
chmod -R 770 $WEBROOT/shared
chmod -R 770 $WEBROOT/workflow/engine/config
chmod -R 770 $WEBROOT/workflow/engine/plugins
chmod 770 $WEBROOT/workflow/engine/content/languages
chmod 770 $WEBROOT/workflow/engine/js/labels
chmod 770 $WEBROOT/workflow/engine/xmlform

# configure apache
a2dissite default
a2ensite processmaker
a2enmod rewrite
a2enmod deflate

