#!/bin/bash -e
# regenerate processmaker mysql passwords

. /etc/default/inithooks

CONF_DB=/var/www/processmaker/shared/sites/workflow/db.php
CONF_DATABASES=/var/www/processmaker/shared/sites/workflow/databases.php

WF_PASSWORD=$(mcookie)
RB_PASSWORD=$(mcookie)
RP_PASSWORD=$(mcookie)

sed -i "s|DB_PASS.*|DB_PASS',        '$WF_PASSWORD' );|" $CONF_DB
sed -i "s|DB_RBAC_PASS.*|DB_RBAC_PASS',   '$RB_PASSWORD' );|" $CONF_DB
sed -i "s|DB_REPORT_PASS.*|DB_REPORT_PASS', '$RP_PASSWORD' );|" $CONF_DB

sed -i "s|^\$dbPass.*|\$dbPass       = '$WF_PASSWORD';|" $CONF_DATABASES
sed -i "s|^\$dbRbacPass.*|\$dbRbacPass   = '$RB_PASSWORD';|" $CONF_DATABASES
sed -i "s|^\$dbReportPass.*|\$dbReportPass = '$RP_PASSWORD';|" $CONF_DATABASES

$INITHOOKS_PATH/bin/mysqlconf.py --user=wf_workflow --pass="$WF_PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=rb_workflow --pass="$RB_PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=rp_workflow --pass="$RP_PASSWORD"

