#!/bin/bash -e
# regenerate processmaker mysql password

. /etc/default/inithooks

CONF_DB=/var/www/processmaker/shared/sites/workflow/db.php
CONF_DATABASES=/var/www/processmaker/shared/sites/workflow/databases.php

WF_PASSWORD=$(mcookie)

sed -i "s|DB_PASS.*|DB_PASS',        '$WF_PASSWORD' );|" $CONF_DB
sed -i "s|DB_RBAC_PASS.*|DB_RBAC_PASS',   '$WF_PASSWORD' );|" $CONF_DB
sed -i "s|DB_REPORT_PASS.*|DB_REPORT_PASS', '$WF_PASSWORD' );|" $CONF_DB

sed -i "s|^\$dbPass.*|\$dbPass       = '$WF_PASSWORD';|" $CONF_DATABASES
sed -i "s|^\$dbRbacPass.*|\$dbRbacPass   = '$WF_PASSWORD';|" $CONF_DATABASES
sed -i "s|^\$dbReportPass.*|\$dbReportPass = '$WF_PASSWORD';|" $CONF_DATABASES

$INITHOOKS_PATH/bin/mysqlconf.py --user=wf_workflow --pass="$WF_PASSWORD"

