#!/bin/bash -e
# set processmaker admin password and email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/processmaker.py --pass="$APP_PASS" --email="$APP_EMAIL"

